import type * as fabric from "fabric";
import { BaseManager } from "./BaseManager";
import { LIMITS } from "../../constants";
import type {
    ExportOptions,
    ExportResult,
    LayerItem,
    FabricObjectWithData,
} from "../../types";

export class ExportManager extends BaseManager {
    // ============ ZOOM ============

    setZoom(zoom: number): void {
        if (!this.editor.canvas) return;

        const clampedZoom = Math.max(LIMITS.minZoom, Math.min(LIMITS.maxZoom, zoom));
        this.editor._zoom = clampedZoom;
        this.editor.canvas.setZoom(clampedZoom);
        this.editor.canvas.renderAll();
        this.editor.emit("zoom:changed", { zoom: clampedZoom });
    }

    zoomIn(): void {
        this.setZoom(this.editor._zoom + LIMITS.zoomStep);
    }

    zoomOut(): void {
        this.setZoom(this.editor._zoom - LIMITS.zoomStep);
    }

    resetZoom(): void {
        this.setZoom(1);
    }

    fitToScreen(): void {
        this.resetZoom();
    }

    // ============ ЭКСПОРТ ============

    async exportImage(options: ExportOptions): Promise<ExportResult> {
        if (!this.editor.canvas) {
            throw new Error("Editor not initialized");
        }

        if (options.withWatermark && this.editor._config.watermark.enabled) {
            await this.addWatermarkToCanvas();
        }

        const dataUrl = this.editor.canvas.toDataURL({
            format: options.format,
            quality: options.quality,
            multiplier: options.multiplier,
        });

        if (options.withWatermark) {
            this.removeWatermarkFromCanvas();
        }

        // Security check: only allow data URLs generated by the canvas
        if (!dataUrl.startsWith("data:image/")) {
            throw new Error("Invalid export data URL");
        }

        const response = await fetch(dataUrl);
        const blob = await response.blob();

        return {
            blob,
            dataUrl,
            width: this.editor._config.width * options.multiplier,
            height: this.editor._config.height * options.multiplier,
        };
    }

    toJSON(): object {
        if (!this.editor.canvas) return {};

        return {
            version: "1.0",
            config: this.editor._config,
            canvas: this.editor.canvas.toJSON(),
            objects: Array.from(this.editor.objects.entries()).map(([id, layer]) => ({
                id,
                name: layer.name,
                type: layer.type,
                visible: layer.visible,
                locked: layer.locked,
            })),
        };
    }

    async loadFromJSON(json: unknown): Promise<void> {
        const data = json as { canvas?: Record<string, unknown>; objects?: LayerItem[] };
        if (!this.editor.canvas) return;

        this.editor.objects.clear();
        this.editor.history.clear();

        if (data.canvas) {
            await this.editor.canvas.loadFromJSON(data.canvas);
        }
        
        this.editor.canvas.getObjects().forEach((obj) => {
            const fabricObj = obj as FabricObjectWithData;
            const fabricData = fabricObj.data;
            if (fabricData?.id) {
                const layerData = data.objects?.find((o) => o.id === fabricData.id);
                const layer: LayerItem = {
                    id: fabricData.id,
                    name: layerData?.name || "Объект",
                    type: fabricData.type,
                    visible: fabricData.visible ?? true,
                    locked: fabricData.locked ?? false,
                    opacity: obj.opacity ?? 1,
                    zIndex: 0,
                    fabricObject: obj,
                };
                this.editor.objects.set(fabricData.id, layer);
            }
        });

        this.editor.canvas.renderAll();
    }

    // ============ WATERMARK СЛУЖЕБНЫЕ ============

    private async addWatermarkToCanvas(): Promise<void> {
        if (!this.editor.canvas || !this.editor._config.watermark.enabled) return;

        const config = this.editor._config.watermark;
        const padding = 20;

        if (config.type === "text" || config.type === "both") {
            const text = new this.fabric.FabricText(config.text || "© Merch CRM", {
                fontSize: 16,
                fill: "#000000",
                opacity: config.opacity,
                selectable: false,
                evented: false,
            } as fabric.TFabricObjectProps);
            
            (text as unknown as { data: Record<string, unknown> }).data = { type: "watermark" };

            const pos = this.calculateWatermarkPosition(text, config.position, padding);
            text.set(pos);
            this.editor.canvas.add(text);
            this.editor.watermarkObject = text;
        }

        if (config.type === "image" || config.type === "both") {
            if (config.imagePath) {
                try {
                    const img = await this.fabric.FabricImage.fromURL(config.imagePath!, { crossOrigin: "anonymous" });
                    
                    const maxSize = Math.min(this.editor._config.width, this.editor._config.height) * 0.15;
                    const scale = maxSize / Math.max(img.width!, img.height!);
                    img.scale(scale * config.scale);

                    img.set({
                        opacity: config.opacity,
                        selectable: false,
                        evented: false,
                    });
                    
                    (img as unknown as { data: Record<string, unknown> }).data = { type: "watermark" };

                    const pos = this.calculateWatermarkPosition(img, config.position, padding);
                    img.set(pos);
                    this.editor.canvas.add(img);
                    this.editor.watermarkObject = img;
                } catch (_error) {
                    // Ignore image load error for watermark
                }
            }
        }
    }

    private removeWatermarkFromCanvas(): void {
        if (this.editor.watermarkObject && this.editor.canvas) {
            this.editor.canvas.remove(this.editor.watermarkObject);
            this.editor.watermarkObject = null;
        }
    }

    private calculateWatermarkPosition(
        obj: fabric.Object,
        position: string,
        padding: number
    ): { left: number; top: number } {
        const objWidth = obj.getScaledWidth();
        const objHeight = obj.getScaledHeight();

        switch (position) {
            case "top-left":
                return { left: padding, top: padding };
            case "top-right":
                return { left: this.editor._config.width - objWidth - padding, top: padding };
            case "bottom-left":
                return { left: padding, top: this.editor._config.height - objHeight - padding };
            case "bottom-right":
                return {
                    left: this.editor._config.width - objWidth - padding,
                    top: this.editor._config.height - objHeight - padding,
                };
            case "center":
                return {
                    left: (this.editor._config.width - objWidth) / 2,
                    top: (this.editor._config.height - objHeight) / 2,
                };
            default:
                return { left: padding, top: padding };
        }
    }
}
