"use client";

import { useState } from "react";
import {
    Plus,
    Ticket,
    Trash2,
    ToggleLeft,
    ToggleRight,
    Calendar,
    Edit3,
    Search,
    X,
    Layers,
    Banknote,
    Percent,
    Coins,
    Truck,
    Gift,
    Download,
    Filter
} from "lucide-react";
import { cn } from "@/lib/utils";
import { Button } from "@/components/ui/button";
import { format } from "date-fns";
import { ru } from "date-fns/locale";
import { useRouter } from "next/navigation";
import {
    togglePromocodeActive,
    deletePromocode,
    createPromocode,
    updatePromocode,
    bulkCreatePromocodes
} from "./actions";
import { ConfirmDialog } from "@/components/ui/confirm-dialog";
import { ResponsiveModal } from "@/components/ui/responsive-modal";
import { PremiumSelect } from "@/components/ui/premium-select";
import { useBranding } from "@/components/branding-provider";
import { useIsMobile } from "@/hooks/use-mobile";

export interface Promocode {
    id: string;
    name: string | null;
    code: string;
    discountType: string;
    value: string;
    isActive: boolean;
    usageCount: number;
    usageLimit: number | null;
    expiresAt: string | Date | null;
    adminComment: string | null;
    minOrderAmount: string | null;
    totalSaved: number;
    createdAt: string | Date;
}

export function PromocodesClient({ initialData }: { initialData: Promocode[] }) {
    const { currencySymbol } = useBranding();
    const isMobile = useIsMobile();
    const router = useRouter();
    const [data, setData] = useState(initialData);
    const [isDialogOpen, setIsDialogOpen] = useState(false);
    const [editingPromo, setEditingPromo] = useState<Promocode | null>(null);
    const [isLoading, setIsLoading] = useState(false);
    const [isBulkDialogOpen, setIsBulkDialogOpen] = useState(false);
    const [searchQuery, setSearchQuery] = useState("");
    const [deleteConfirmId, setDeleteConfirmId] = useState<string | null>(null);
    const [discountType, setDiscountType] = useState("percentage");
    const [bulkDiscountType, setBulkDiscountType] = useState("percentage");
    const [promoName, setPromoName] = useState("");
    const [promoCode, setPromoCode] = useState("");
    const [isCodeAutoGenerated, setIsCodeAutoGenerated] = useState(true);
    const [statusFilter, setStatusFilter] = useState("all");
    const [typeFilter, setTypeFilter] = useState("all");

    const generateCode = (name: string) => {
        return name
            .toUpperCase()
            .replace(/[\s\-_]+/g, "")
            .replace(/[^A-Z0-9А-Я]/gi, "")
            .slice(0, 12);
    };

    const handleNameChange = (val: string) => {
        setPromoName(val);
        if (isCodeAutoGenerated) {
            setPromoCode(generateCode(val));
        }
    };

    const handleCodeChange = (val: string) => {
        setPromoCode(val.toUpperCase());
        setIsCodeAutoGenerated(val === "" || val === generateCode(promoName));
    };

    const handleToggle = async (id: string, current: boolean) => {
        const res = await togglePromocodeActive(id, !current);
        if (res.success) {
            setData(prev => prev.map(p => p.id === id ? { ...p, isActive: !current } : p));
        }
    };

    const handleDelete = (id: string) => {
        setDeleteConfirmId(id);
    };

    const confirmDelete = async () => {
        if (!deleteConfirmId) return;
        const res = await deletePromocode(deleteConfirmId);
        setDeleteConfirmId(null);
        if (res.success) {
            setData(prev => prev.filter(p => p.id !== deleteConfirmId));
        }
    };

    const handleOpenEdit = (promo: Promocode) => {
        setEditingPromo(promo);
        setPromoName(promo.name || "");
        setPromoCode(promo.code);
        setIsCodeAutoGenerated(false);
        setDiscountType(promo.discountType === 'fixed_amount' ? 'fixed' : promo.discountType);
        setIsDialogOpen(true);
    };

    const handleOpenCreate = () => {
        setEditingPromo(null);
        setPromoName("");
        setPromoCode("");
        setIsCodeAutoGenerated(true);
        setDiscountType("percentage");
        setIsDialogOpen(true);
    };

    const filteredData = data.filter(p => {
        const matchesSearch = p.code.toLowerCase().includes(searchQuery.toLowerCase()) ||
            (p.name && p.name.toLowerCase().includes(searchQuery.toLowerCase()));

        const matchesStatus = statusFilter === "all" ||
            (statusFilter === "active" ? p.isActive : !p.isActive);

        const matchesType = typeFilter === "all" || p.discountType === typeFilter;

        return matchesSearch && matchesStatus && matchesType;
    });

    const handleExport = () => {
        const headers = ["Название", "Код", "Тип", "Значение", "Активен", "Использовано", "Лимит", `Сэкономлено (${currencySymbol})`, "Истекает", "Комментарий"];
        const rows = filteredData.map(p => [
            p.name || "",
            p.code,
            p.discountType,
            p.value,
            p.isActive ? "Да" : "Нет",
            p.usageCount,
            p.usageLimit || "∞",
            p.totalSaved,
            p.expiresAt ? format(new Date(p.expiresAt), "dd.MM.yyyy") : "Бессрочно",
            p.adminComment || ""
        ]);

        const csvContent = [
            headers.join(","),
            ...rows.map(r => r.map(cell => `"${cell}"`).join(","))
        ].join("\n");

        const blob = new Blob(["\uFEFF" + csvContent], { type: "text/csv;charset=utf-8;" });
        const link = document.createElement("a");
        const url = URL.createObjectURL(blob);
        link.setAttribute("href", url);
        link.setAttribute("download", `promocodes_export_${format(new Date(), "yyyy-MM-dd")}.csv`);
        link.style.visibility = "hidden";
        document.body.appendChild(link);
        link.click();
        document.body.removeChild(link);
    };

    return (
        <div className="space-y-8 animate-in fade-in slide-in-from-bottom-2 duration-700">
            <div className="flex flex-col md:flex-row md:items-center justify-end gap-6">

                <div className="flex items-center gap-3">
                    <div className="relative flex-1 md:min-w-[280px]">
                        <Search className="absolute left-4 top-1/2 -translate-y-1/2 w-4 h-4 text-slate-400" />
                        <input
                            type="text"
                            placeholder="ПОИСК КОДА..."
                            value={searchQuery}
                            onChange={(e) => setSearchQuery(e.target.value)}
                            className="w-full h-12 pl-12 pr-4 bg-white border border-slate-200 rounded-full text-[11px] font-bold tracking-wider focus:ring-4 focus:ring-primary/10 focus:border-primary/50 transition-all placeholder:text-slate-300 shadow-sm"
                        />
                    </div>
                    <Button
                        onClick={() => setIsBulkDialogOpen(true)}
                        variant="outline"
                        className="h-12 w-12 sm:w-auto sm:px-6 rounded-full sm:rounded-2xl font-bold border-slate-200 text-slate-600 hover:bg-slate-50 transition-all flex items-center justify-center sm:gap-2"
                        title="Массовая генерация"
                    >
                        <Layers className="w-5 h-5 opacity-60" />
                        <span className="hidden sm:inline">Массовая генерация</span>
                    </Button>
                    <Button
                        onClick={handleOpenCreate}
                        variant="default"
                        className="h-12 w-12 sm:w-auto sm:px-8 rounded-full sm:rounded-2xl font-bold shadow-lg shadow-primary/25 hover:shadow-primary/35 transition-all flex items-center justify-center sm:gap-2 active:scale-[0.98]"
                        title="Создать"
                    >
                        <Plus className="w-5 h-5 pointer-events-none" />
                        <span className="hidden sm:inline">Создать</span>
                    </Button>
                    <Button
                        onClick={handleExport}
                        variant="outline"
                        className="h-12 w-12 p-0 rounded-2xl border-slate-200 text-slate-600 hover:bg-slate-50 transition-all flex items-center justify-center"
                        title="Экспорт в CSV"
                    >
                        <Download className="w-5 h-5 opacity-60" />
                    </Button>
                </div>
            </div>

            {/* Панель фильтров */}
            <div className="flex flex-wrap items-center gap-4 bg-slate-50/50 p-4 rounded-[20px] border border-slate-100">
                <div className="flex items-center gap-2 text-slate-400 mr-2">
                    <Filter className="w-4 h-4" />
                    <span className="text-[10px] font-bold uppercase tracking-wider">Фильтры:</span>
                </div>

                <div className="w-[180px]">
                    <PremiumSelect
                        options={[
                            { id: "all", title: "Все статусы" },
                            { id: "active", title: "Только активные" },
                            { id: "paused", title: "На паузе" }
                        ]}
                        value={statusFilter}
                        onChange={setStatusFilter}
                        variant="minimal"
                    />
                </div>

                <div className="w-[200px]">
                    <PremiumSelect
                        options={[
                            { id: "all", title: "Все типы скидок" },
                            { id: "percentage", title: "Процент %" },
                            { id: "fixed", title: `Фикс. сумма ${currencySymbol}` },
                            { id: "free_shipping", title: "Беспл. доставка" },
                            { id: "gift", title: "Подарок" }
                        ]}
                        value={typeFilter}
                        onChange={setTypeFilter}
                        variant="minimal"
                    />
                </div>

                <div className="ml-auto text-slate-400 text-[10px] font-bold uppercase tracking-wider">
                    Найдено: {filteredData.length}
                </div>
            </div>

            {/* Premium Grid */}
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-5">
                {filteredData.map((promo) => (
                    <div
                        key={promo.id}
                        className={cn(
                            "group bg-white rounded-[12px] border border-slate-200 p-5 hover:shadow-xl hover:shadow-slate-200/50 transition-all duration-300 relative overflow-hidden flex flex-col justify-between",
                            !promo.isActive && "opacity-75"
                        )}
                    >
                        {/* High-end decorative background */}
                        <div className="absolute -top-10 -right-10 w-32 h-32 bg-primary/5 rounded-full blur-2xl group-hover:bg-primary/10 transition-colors duration-500" />

                        <div>
                            <div className="flex items-start justify-between mb-4 relative z-10">
                                <div className="flex items-center gap-2">
                                    <div className={cn(
                                        "px-2.5 py-1 rounded-full text-[9px] font-bold tracking-normal border",
                                        promo.isActive
                                            ? "bg-emerald-50 text-emerald-600 border-emerald-100"
                                            : "bg-slate-50 text-slate-400 border-slate-200"
                                    )}>
                                        {promo.isActive ? "● АКТИВЕН" : "○ ПАУЗА"}
                                    </div>
                                </div>
                                <div className="flex items-center gap-0.5 opacity-0 group-hover:opacity-100 transition-opacity">
                                    <button
                                        onClick={() => handleOpenEdit(promo)}
                                        className="p-1.5 text-slate-400 hover:text-primary transition-colors"
                                    >
                                        <Edit3 className="w-4 h-4" />
                                    </button>
                                    <button
                                        onClick={() => handleToggle(promo.id, promo.isActive)}
                                        className="p-1.5 text-slate-400 hover:text-emerald-500 transition-colors"
                                    >
                                        {promo.isActive ? <ToggleRight className="w-5 h-5 text-emerald-500" /> : <ToggleLeft className="w-5 h-5" />}
                                    </button>
                                    <button
                                        onClick={() => handleDelete(promo.id)}
                                        className="p-1.5 rounded-[var(--radius-inner)] text-slate-400 btn-destructive-ghost"
                                    >
                                        <Trash2 className="w-4 h-4" />
                                    </button>
                                </div>
                            </div>

                            <div className="relative z-10">
                                <div className="text-[10px] font-bold text-slate-400 tracking-normal mb-1">Название / Код</div>
                                <div className="mb-4">
                                    <div className="text-base font-bold text-slate-900 tracking-normal group-hover:text-primary transition-colors line-clamp-1">
                                        {promo.name || "Без названия"}
                                    </div>
                                    <div className="text-[11px] font-black text-slate-400 tracking-wider">
                                        {promo.code}
                                    </div>
                                </div>

                                <div className="grid grid-cols-2 gap-4 pb-4 border-b border-slate-200">
                                    <div>
                                        <div className="text-[9px] font-bold text-slate-300 tracking-normal mb-1">Выгода</div>
                                        <div className="text-lg font-bold text-primary">
                                            {promo.discountType === 'percentage' ? `${promo.value}%` :
                                                promo.discountType === 'fixed' ? `${promo.value} ${currencySymbol}` :
                                                    promo.discountType === 'free_shipping' ? `0 ${currencySymbol}` : "GIFT"}
                                        </div>
                                    </div>
                                    <div>
                                        <div className="text-[9px] font-bold text-slate-300 tracking-normal mb-1">Лимит</div>
                                        <div className="text-lg font-bold text-slate-900">
                                            {promo.usageCount}<span className="text-slate-200"> / </span><span className="text-slate-400">{promo.usageLimit || "∞"}</span>
                                        </div>
                                    </div>
                                </div>
                                <div className="pt-4">
                                    <div className="text-[9px] font-bold text-slate-300 tracking-normal mb-1">Сэкономлено клиентами</div>
                                    <div className="flex items-center gap-2">
                                        <div className="w-8 h-8 rounded-lg bg-emerald-50 flex items-center justify-center">
                                            <Banknote className="w-4 h-4 text-emerald-500" />
                                        </div>
                                        <div className="text-lg font-bold text-slate-900">
                                            {Number(promo.totalSaved).toLocaleString('ru-RU')} {currencySymbol}
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div className="pt-4 flex items-center justify-between relative z-10">
                            <div className="flex items-center gap-2 text-slate-400">
                                <Calendar className="w-3.5 h-3.5 opacity-60" />
                                <span className="text-[9px] font-bold  tracking-normal">
                                    {promo.expiresAt
                                        ? format(new Date(promo.expiresAt), "dd.MM.yyyy", { locale: ru })
                                        : "БЕССРОЧНО"
                                    }
                                </span>
                            </div>
                            <div className={cn(
                                "px-2 py-0.5 rounded text-[8px] font-bold tracking-normal uppercase",
                                promo.discountType === 'percentage' ? "bg-emerald-50 text-emerald-600 border-emerald-100" :
                                    promo.discountType === 'fixed' ? "bg-blue-50 text-blue-600 border-blue-100" :
                                        promo.discountType === 'gift' ? "bg-rose-50 text-rose-600 border-rose-100" : "bg-amber-50 text-amber-600 border-amber-100"
                            )}>
                                <div className="flex items-center gap-1">
                                    {promo.discountType === 'percentage' && <Percent className="w-2.5 h-2.5" />}
                                    {promo.discountType === 'fixed' && <Coins className="w-2.5 h-2.5" />}
                                    {promo.discountType === 'free_shipping' && <Truck className="w-2.5 h-2.5" />}
                                    {promo.discountType === 'gift' && <Gift className="w-2.5 h-2.5" />}
                                    {promo.discountType === 'percentage' ? "Процент" :
                                        promo.discountType === 'fixed' ? "Фикс. сумма" :
                                            promo.discountType === 'gift' ? "Подарок" : "Доставка"}
                                </div>
                            </div>
                        </div>

                    </div>
                ))}

                {filteredData.length === 0 && (
                    <div className="col-span-full py-24 bg-slate-50/50 rounded-[12px] border-2 border-dashed border-slate-200 flex flex-col items-center justify-center">
                        <div className="w-20 h-20 bg-white rounded-[12px] shadow-sm flex items-center justify-center mb-6">
                            <Ticket className="w-10 h-10 text-slate-200" />
                        </div>
                        <h3 className="text-base font-bold text-slate-400  tracking-normal">Ничего не найдено</h3>
                        <p className="text-[11px] text-slate-300 font-bold mt-2  tracking-normal">Измените условия поиска или создайте новый промокод</p>
                    </div>
                )}
            </div>

            {/* Premium Dialog Overlay */}
            <ResponsiveModal
                isOpen={isDialogOpen}
                onClose={() => setIsDialogOpen(false)}
                showVisualTitle={false}
                className="sm:max-w-[520px] p-0 overflow-hidden"
            >
                <div className="flex flex-col h-full overflow-hidden">
                    <div className="p-6 sm:p-8 flex items-center justify-between border-b border-slate-50 bg-white/80 backdrop-blur-md sticky top-0 z-20">
                        <div className="flex items-center gap-4">
                            <div className="w-12 h-12 sm:w-14 sm:h-14 rounded-2xl bg-primary/10 flex items-center justify-center">
                                <Ticket className="w-6 h-6 sm:w-7 sm:h-7 text-primary" />
                            </div>
                            <div>
                                <h2 className="text-xl sm:text-2xl font-bold text-slate-900 tracking-tight leading-tight">
                                    {editingPromo ? "Редактировать" : "Новый промокод"}
                                </h2>
                                <p className="text-slate-400 text-[10px] sm:text-xs font-bold uppercase tracking-widest mt-0.5">
                                    Параметры промокода
                                </p>
                            </div>
                        </div>
                        <button
                            onClick={() => setIsDialogOpen(false)}
                            className="w-10 h-10 rounded-full bg-slate-50 text-slate-400 hover:text-slate-900 flex items-center justify-center transition-all active:scale-95"
                        >
                            <X className="w-5 h-5" />
                        </button>
                    </div>

                    <div className="flex-1 p-6 sm:p-8 overflow-y-auto custom-scrollbar">
                        <form id="promocode-form" action={async (formData) => {
                            setIsLoading(true);
                            const values = {
                                name: formData.get("name") as string,
                                code: (formData.get("code") as string).toUpperCase(),
                                discountType: formData.get("discountType") as "percentage" | "fixed" | "free_shipping" | "gift",
                                value: Number(formData.get("value")),
                                minOrderAmount: Number(formData.get("minOrderAmount")),
                                usageLimit: formData.get("usageLimit")?.toString(),
                                expiresAt: formData.get("expiresAt")?.toString() || null,
                                adminComment: formData.get("adminComment") as string
                            };

                            const res = editingPromo
                                ? await updatePromocode(editingPromo.id, values)
                                : await createPromocode(values);

                            setIsLoading(false);
                            if (res.success) {
                                setIsDialogOpen(false);
                                router.refresh();
                            }
                        }} className="space-y-6">
                            <div className="grid grid-cols-1 sm:grid-cols-[1fr,120px] gap-4">
                                <div className="space-y-2">
                                    <label className="text-[11px] sm:text-[13px] font-bold text-slate-700 ml-1">Название</label>
                                    <input
                                        name="name"
                                        required
                                        value={promoName}
                                        onChange={(e) => handleNameChange(e.target.value)}
                                        className="w-full px-5 py-3.5 bg-slate-50 border-none rounded-[var(--radius-inner)] text-sm font-bold focus:ring-4 focus:ring-primary/5 transition-all placeholder:text-slate-300"
                                        placeholder="Напр. Летняя распродажа"
                                    />
                                </div>
                                <div className="space-y-2">
                                    <label className="text-[11px] sm:text-[13px] font-bold text-slate-700 ml-1">Код</label>
                                    <input
                                        name="code"
                                        required
                                        value={promoCode}
                                        onChange={(e) => handleCodeChange(e.target.value)}
                                        className="w-full px-5 py-3.5 bg-slate-50 border-none rounded-[var(--radius-inner)] text-sm font-bold focus:ring-4 focus:ring-primary/5 transition-all placeholder:text-slate-300 uppercase text-center tracking-wider"
                                        placeholder="SALE26"
                                    />
                                </div>
                            </div>

                            <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                                <div className="space-y-2">
                                    <label className="text-[11px] sm:text-[13px] font-bold text-slate-700 ml-1">Тип скидки</label>
                                    <input type="hidden" name="discountType" value={discountType} />
                                    <PremiumSelect
                                        options={[
                                            { id: "percentage", title: "Процент %" },
                                            { id: "fixed", title: `Фикс. сумма ${currencySymbol}` },
                                            { id: "free_shipping", title: "Беспл. доставка" },
                                            { id: "gift", title: "Подарок" }
                                        ]}
                                        value={discountType}
                                        onChange={setDiscountType}
                                        autoLayout={false}
                                    />
                                </div>
                                <div className="space-y-2">
                                    <label className="text-[11px] sm:text-[13px] font-bold text-slate-700 ml-1">Значение / ID Подарка</label>
                                    <input
                                        name="value"
                                        type="number"
                                        required
                                        defaultValue={editingPromo?.value}
                                        className="w-full px-5 py-3.5 bg-slate-50 border-none rounded-[var(--radius-inner)] text-sm font-bold focus:ring-4 focus:ring-primary/5 transition-all"
                                        placeholder="10"
                                    />
                                </div>
                            </div>

                            <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                                <div className="space-y-2">
                                    <label className="text-[11px] sm:text-[13px] font-bold text-slate-700 ml-1">Мин. сумма заказа</label>
                                    <input
                                        name="minOrderAmount"
                                        type="number"
                                        defaultValue={editingPromo?.minOrderAmount || "0"}
                                        className="w-full px-5 py-3.5 bg-slate-50 border-none rounded-[var(--radius-inner)] text-sm font-bold focus:ring-4 focus:ring-primary/5 transition-all"
                                        placeholder="0"
                                    />
                                </div>
                            </div>

                            <div className="space-y-2">
                                <label className="text-[11px] sm:text-[13px] font-bold text-slate-700 ml-1">Комментарий (внутренний)</label>
                                <textarea
                                    name="adminComment"
                                    defaultValue={editingPromo?.adminComment || ""}
                                    rows={2}
                                    className="w-full px-5 py-3.5 bg-slate-50 border-none rounded-[var(--radius-inner)] text-sm font-bold focus:ring-4 focus:ring-primary/5 transition-all resize-none placeholder:text-slate-300"
                                    placeholder="Например: Выдан блогеру @ivanov за рекламу"
                                />
                            </div>

                            <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                                <div className="space-y-2">
                                    <label className="text-[11px] sm:text-[13px] font-bold text-slate-700 ml-1">Лимит использований</label>
                                    <input
                                        name="usageLimit"
                                        type="number"
                                        defaultValue={editingPromo?.usageLimit || ""}
                                        className="w-full px-5 py-3.5 bg-slate-50 border-none rounded-[var(--radius-inner)] text-sm font-bold focus:ring-4 focus:ring-primary/5 transition-all placeholder:text-slate-300"
                                        placeholder="Безлимитно"
                                    />
                                </div>
                                <div className="space-y-2">
                                    <label className="text-[11px] sm:text-[13px] font-bold text-slate-700 ml-1">Дата истечения</label>
                                    <div className="relative">
                                        <input
                                            name="expiresAt"
                                            type="date"
                                            defaultValue={editingPromo?.expiresAt ? format(new Date(editingPromo.expiresAt), "yyyy-MM-dd") : ""}
                                            className="w-full px-5 py-3.5 bg-slate-50 border-none rounded-[var(--radius-inner)] text-sm font-bold focus:ring-4 focus:ring-primary/5 transition-all appearance-none"
                                        />
                                        <Calendar className="absolute right-4 top-1/2 -translate-y-1/2 w-4 h-4 text-slate-300 pointer-events-none" />
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>

                    <div className="p-6 sm:p-8 bg-white/80 backdrop-blur-md border-t border-slate-50 sticky bottom-0 z-20">
                        <button
                            form="promocode-form"
                            type="submit"
                            disabled={isLoading}
                            className="w-full btn-dark text-white py-4 rounded-[var(--radius-inner)] text-sm font-bold transition-all active:scale-[0.98] disabled:opacity-50 shadow-lg shadow-slate-900/10 flex items-center justify-center gap-2 border-none"
                        >
                            {isLoading ? "Сохранение..." : (editingPromo ? "Сохранить изменения" : "Создать промокод")}
                        </button>
                    </div>
                </div>
            </ResponsiveModal>

            {/* Bulk Generation Dialog */}
            <ResponsiveModal
                isOpen={isBulkDialogOpen}
                onClose={() => setIsBulkDialogOpen(false)}
                showVisualTitle={false}
                className="sm:max-w-[520px] p-0 overflow-hidden"
            >
                <div className="flex flex-col h-full overflow-hidden">
                    <div className="p-6 sm:p-8 flex items-center justify-between border-b border-slate-50 bg-white/80 backdrop-blur-md sticky top-0 z-20">
                        <div className="flex items-center gap-4">
                            <div className="w-12 h-12 sm:w-14 sm:h-14 rounded-2xl bg-primary/10 flex items-center justify-center">
                                <Layers className="w-6 h-6 sm:w-7 sm:h-7 text-primary" />
                            </div>
                            <div>
                                <h2 className="text-xl sm:text-2xl font-bold text-slate-900 tracking-tight leading-tight">
                                    Массовая генерация
                                </h2>
                                <p className="text-slate-400 text-[10px] sm:text-xs font-bold uppercase tracking-widest mt-0.5">
                                    Создание группы уникальных кодов
                                </p>
                            </div>
                        </div>
                        <button
                            onClick={() => setIsBulkDialogOpen(false)}
                            className="w-10 h-10 rounded-full bg-slate-50 text-slate-400 hover:text-slate-900 flex items-center justify-center transition-all active:scale-95"
                        >
                            <X className="w-5 h-5" />
                        </button>
                    </div>

                    <div className="flex-1 p-6 sm:p-8 overflow-y-auto custom-scrollbar">
                        <form id="bulk-promocode-form" action={async (formData) => {
                            setIsLoading(true);
                            const count = Number(formData.get("count"));
                            const prefix = (formData.get("prefix") as string).toUpperCase();
                            const values = {
                                name: formData.get("name") as string,
                                code: "BULK", // Not used for bulk
                                discountType: formData.get("discountType") as "percentage" | "fixed" | "free_shipping" | "gift",
                                value: Number(formData.get("value")),
                                minOrderAmount: Number(formData.get("minOrderAmount")),
                                usageLimit: "1", // One-time use for each bulk code
                                expiresAt: formData.get("expiresAt")?.toString() || null,
                            };

                            const res = await bulkCreatePromocodes(count, prefix, values);
                            setIsLoading(false);
                            if (res.success) {
                                setIsBulkDialogOpen(false);
                                router.refresh();
                            }
                        }} className="space-y-6">
                            <div className="space-y-2">
                                <label className="text-[11px] sm:text-[13px] font-bold text-slate-700 ml-1">Название группы</label>
                                <input name="name" required className="w-full px-5 py-3.5 bg-slate-50 border-none rounded-[var(--radius-inner)] text-sm font-bold focus:ring-4 focus:ring-primary/5 transition-all placeholder:text-slate-300" placeholder="Напр. Акция для блогеров" />
                            </div>

                            <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                                <div className="space-y-2">
                                    <label className="text-[11px] sm:text-[13px] font-bold text-slate-700 ml-1">Префикс (напр. SALE-)</label>
                                    <input name="prefix" required className="w-full px-5 py-3.5 bg-slate-50 border-none rounded-[var(--radius-inner)] text-sm font-bold focus:ring-4 focus:ring-primary/5 transition-all uppercase placeholder:text-slate-300 tracking-wider" placeholder="SALE-" />
                                </div>
                                <div className="space-y-2">
                                    <label className="text-[11px] sm:text-[13px] font-bold text-slate-700 ml-1">Количество кодов</label>
                                    <input name="count" type="number" required min="1" max="100" defaultValue="10" className="w-full px-5 py-3.5 bg-slate-50 border-none rounded-[var(--radius-inner)] text-sm font-bold focus:ring-4 focus:ring-primary/5 transition-all" />
                                </div>
                            </div>

                            <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                                <div className="space-y-2">
                                    <label className="text-[11px] sm:text-[13px] font-bold text-slate-700 ml-1">Тип скидки</label>
                                    <input type="hidden" name="discountType" value={bulkDiscountType} />
                                    <PremiumSelect
                                        options={[
                                            { id: "percentage", title: "Процент %" },
                                            { id: "fixed", title: `Фикс. сумма ${currencySymbol}` },
                                            { id: "free_shipping", title: "Беспл. доставка" },
                                            { id: "gift", title: "Подарок" }
                                        ]}
                                        value={bulkDiscountType}
                                        onChange={setBulkDiscountType}
                                        autoLayout={false}
                                    />
                                </div>
                                <div className="space-y-2">
                                    <label className="text-[11px] sm:text-[13px] font-bold text-slate-700 ml-1">Значение</label>
                                    <input name="value" type="number" required className="w-full px-5 py-3.5 bg-slate-50 border-none rounded-[var(--radius-inner)] text-sm font-bold focus:ring-4 focus:ring-primary/5 transition-all placeholder:text-slate-300" placeholder="10" />
                                </div>
                            </div>

                            <div className="space-y-2">
                                <label className="text-[11px] sm:text-[13px] font-bold text-slate-700 ml-1">Дата истечения</label>
                                <div className="relative">
                                    <input name="expiresAt" type="date" className="w-full px-5 py-3.5 bg-slate-50 border-none rounded-[var(--radius-inner)] text-sm font-bold focus:ring-4 focus:ring-primary/5 transition-all appearance-none" />
                                    <Calendar className="absolute right-4 top-1/2 -translate-y-1/2 w-4 h-4 text-slate-300 pointer-events-none" />
                                </div>
                            </div>
                        </form>
                    </div>

                    <div className="p-6 sm:p-8 bg-white/80 backdrop-blur-md border-t border-slate-50 sticky bottom-0 z-20">
                        <button
                            form="bulk-promocode-form"
                            type="submit"
                            disabled={isLoading}
                            className="w-full btn-dark text-white py-4 rounded-[var(--radius-inner)] text-sm font-bold transition-all active:scale-[0.98] disabled:opacity-50 shadow-lg shadow-slate-900/10 flex items-center justify-center gap-2 border-none"
                        >
                            {isLoading ? "Генерация..." : "Сгенерировать коды"}
                        </button>
                    </div>
                </div>
            </ResponsiveModal>

            <ConfirmDialog
                isOpen={!!deleteConfirmId}
                onClose={() => setDeleteConfirmId(null)}
                onConfirm={confirmDelete}
                title="Удаление промокода"
                description="Вы уверены, что хотите удалить этот промокод? Это действие нельзя отменить."
                confirmText="Удалить"
                variant="destructive"
            />
        </div>
    );
}
